"""fix null

Revision ID: 015f73812eea
Revises: df77b1a540be
Create Date: 2024-11-09 21:29:59.101965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015f73812eea'
down_revision = 'df77b1a540be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('correctResult', schema=None) as batch_op:
        batch_op.alter_column('true_text',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('correctResult', schema=None) as batch_op:
        batch_op.alter_column('true_text',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
