"""add duration

Revision ID: 18d7a3825cf6
Revises: 748d08154cc2
Create Date: 2024-11-09 15:51:01.202422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d7a3825cf6'
down_revision = '748d08154cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recognitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recognition_duration', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('recognized_part_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('recognized_order_number', sa.String(length=50), nullable=True))
        batch_op.drop_column('recognized_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recognitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recognized_text', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('recognized_order_number')
        batch_op.drop_column('recognized_part_number')
        batch_op.drop_column('recognition_duration')

    # ### end Alembic commands ###
