"""add recognitions

Revision ID: 30e5789fa434
Revises: b242617a40f5
Create Date: 2024-11-08 23:23:21.538951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e5789fa434'
down_revision = 'b242617a40f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recognitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('recognized_image_path', sa.String(length=255), nullable=True),
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('correct_part_number', sa.String(length=50), nullable=True),
    sa.Column('correct_order_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['detail_id'], ['details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recognitions')
    # ### end Alembic commands ###
