"""add correctResult

Revision ID: 35b55476fd26
Revises: 18d7a3825cf6
Create Date: 2024-11-09 19:43:33.405914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35b55476fd26'
down_revision = '18d7a3825cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correctResult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('predicted_text', sa.String(length=255), nullable=False),
    sa.Column('true_text', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('correctResult')
    # ### end Alembic commands ###
