"""add recognized_text

Revision ID: 748d08154cc2
Revises: 84024b54b6fd
Create Date: 2024-11-09 08:37:38.831422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748d08154cc2'
down_revision = '84024b54b6fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recognitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recognized_text', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recognitions', schema=None) as batch_op:
        batch_op.drop_column('recognized_text')

    # ### end Alembic commands ###
