"""fix

Revision ID: b242617a40f5
Revises: a73ade7b3932
Create Date: 2024-11-08 21:26:36.072132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b242617a40f5'
down_revision = 'a73ade7b3932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('details', schema=None) as batch_op:
        batch_op.alter_column('order_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('details', schema=None) as batch_op:
        batch_op.alter_column('order_number',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
